package user;

/**
 * Created by mamadou on 7/9/16.
 */
public enum Competence {
    CHEMICAL_ENGINEERING, COMPUTER_ENGINEERING, CIVIL_ENGINEERING, MECHANICAL_ENGINEERING,
    SOFTWARE_ENGINEERING, MATHEMATICS, PHYSICS, CHEMISTRY, BIOLOGY, SOCIAL_SCIENCES
}
